In [25]:
import paho.mqtt.client as mqtt
import time
import pandas as pd
from datetime import datetime
# This is the Publisher


#https://www.ev3dev.org/docs/tutorials/sending-and-receiving-messages-with-mqtt/

client = mqtt.Client()
client.connect('34.175.93.216',1883,60)
# reading from the file

df = pd.read_csv("../data/datasets/online.data")

df.sort_values(["date"])

df_in = df.loc[df["label"] == "inside"]
df_in = df_in.drop(["label"], axis=1)

df_out = df.loc[df["label"] == "outside"]
df_out = df_out.drop(["label"], axis=1)

#df_in = df_in.set_index("date")
#df_out = df_out.set_index("date")
display(df_in)
display(df_out)

                     date  temperature
1     2020-12-01 00:00:00       24.250
2     2020-12-01 00:30:00       24.187
5     2020-12-01 01:00:00       24.500
7     2020-12-01 01:30:00       24.250
9     2020-12-01 02:00:00       24.562
...                   ...          ...
2966  2020-12-31 21:30:00       21.812
2968  2020-12-31 22:00:00       21.750
2970  2020-12-31 22:30:00       21.937
2972  2020-12-31 23:00:00       22.187
2975  2020-12-31 23:30:00       22.062

[1488 rows x 2 columns]

                     date  temperature
0     2020-12-01 00:00:00       15.250
3     2020-12-01 00:30:00       15.367
4     2020-12-01 01:00:00       14.383
6     2020-12-01 01:30:00       13.567
8     2020-12-01 02:00:00       13.156
...                   ...          ...
2967  2020-12-31 21:30:00       13.767
2969  2020-12-31 22:00:00       15.011
2971  2020-12-31 22:30:00       15.300
2973  2020-12-31 23:00:00       15.250
2974  2020-12-31 23:30:00       14.494

[1488 rows x 2 columns]

In [31]:

i_in = 0
i_out = 0
while i_in < len(df_in) and i_out < len(df_out):

    if i_in < len(df_in):
        in_val = df_in.to_numpy()[i_in]

    if i_out < len(df_out):
        out_val = df_out.to_numpy()[i_out]

    out_date = out_val[0]
    out_temp = out_val[1]

    in_date = out_val[0]
    in_temp = out_val[1]

    # 2020-12-31 19:30:00,11.689,outside
    req_str_out = f"{out_date},{out_temp},outside"
    req_str_in = f"{in_date},{in_temp},inside"

    print(req_str_out)
    print(req_str_in)

    if datetime.strptime(in_date, f"%Y-%m-%d %H:%M:%S") == datetime.strptime(out_date, f"%Y-%m-%d %H:%M:%S"):
        client.publish("idc/fc55309", req_str_out)
        client.publish("idc/fc55309", req_str_in)
        i_in += 1
        i_out += 1
    elif datetime.strptime(in_date, f"%Y-%m-%d %H:%M:%S") >= datetime.strptime(out_date, f"%Y-%m-%d %H:%M:%S"):
        client.publish("idc/fc55309", req_str_out)
        i_out += 1
    elif datetime.strptime(in_date, f"%Y-%m-%d %H:%M:%S") <= datetime.strptime(out_date, f"%Y-%m-%d %H:%M:%S"):
        client.publish("idc/fc55309", req_str_in)
        i_in += 1
    else:
        raise
    time.sleep(3)
client.disconnect()

2020-12-01 00:00:00,15.25,outside
2020-12-01 00:00:00,15.25,inside
2020-12-01 00:30:00,15.367,outside
2020-12-01 00:30:00,15.367,inside
2020-12-01 01:00:00,14.383,outside
2020-12-01 01:00:00,14.383,inside
2020-12-01 01:30:00,13.567,outside
2020-12-01 01:30:00,13.567,inside
2020-12-01 02:00:00,13.156,outside
2020-12-01 02:00:00,13.156,inside
2020-12-01 02:30:00,12.922,outside
2020-12-01 02:30:00,12.922,inside
2020-12-01 03:00:00,12.189,outside
2020-12-01 03:00:00,12.189,inside
2020-12-01 03:30:00,12.283,outside
2020-12-01 03:30:00,12.283,inside
2020-12-01 04:00:00,12.072,outside
2020-12-01 04:00:00,12.072,inside
2020-12-01 04:30:00,11.411,outside
2020-12-01 04:30:00,11.411,inside
2020-12-01 05:00:00,11.5,outside
2020-12-01 05:00:00,11.5,inside
2020-12-01 05:30:00,11.656,outside
2020-12-01 05:30:00,11.656,inside
2020-12-01 06:00:00,11.528,outside
2020-12-01 06:00:00,11.528,inside
2020-12-01 06:30:00,11.144,outside
2020-12-01 06:30:00,11.144,inside
2020-12-01 07:00:00,11.306,outside
2020-12-01 07:00:00,11.306,inside
2020-12-01 07:30:00,11.028,outside
2020-12-01 07:30:00,11.028,inside
2020-12-01 08:00:00,10.111,outside
2020-12-01 08:00:00,10.111,inside
2020-12-01 08:30:00,9.1,outside
2020-12-01 08:30:00,9.1,inside
2020-12-01 09:00:00,8.772,outside
2020-12-01 09:00:00,8.772,inside
2020-12-01 09:30:00,9.106,outside
2020-12-01 09:30:00,9.106,inside
2020-12-01 10:00:00,10.1,outside
2020-12-01 10:00:00,10.1,inside
2020-12-01 10:30:00,9.056,outside
2020-12-01 10:30:00,9.056,inside
2020-12-01 11:00:00,9.483,outside
2020-12-01 11:00:00,9.483,inside

KeyboardInterrupt: